anguage: go

sudo: false

go:
  - "1.16.x"
  - tip

env:
  - GO111MODULE=on

install: true

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - ulimit -n 2048 ; go test -v ./... -covermode=count -coverprofile=profile.cov.tmp
  - cat profile.cov.tmp | grep -v "generated" > profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci